#!/bin/sh
"/cygdrive/c/Program Files/nodejs/node" "/Documents and Settings/Beak/Application Data/npm/node_modules/jshint/bin/hint" --config=lint-config.js src/js/*.js && 
"/cygdrive/c/Program Files/nodejs/node" ../../resources/r.js -o src/build.js && \
chmod -R og+r ../out/* * && \
scp ../out/auth.html ../out/index.html ../out/weft.css duerig@jonathonduerig.com:/var/www/weft &&
scp ../out/js/weft.js duerig@jonathonduerig.com:/var/www/weft/js

